# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: push

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build-cjs

      - name: Run Tests
        run: npm run test-ci

      - name: Run Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  windows:
    needs: linux

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build-cjs

      - name: Run Tests
        run: npm run test-ci

      - name: Run Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
